package com.aa_software.farm_adventure.model.selectable.plot;

public enum Irrigation {
	RIGHT, LEFT_RIGHT, TOP, TOP_RIGHT, TOP_LEFT_RIGHT, TOP_BOTTOM, TOP_RIGHT_BOTTOM, TOP_LEFT_RIGHT_BOTTOM, TOP_LEFT_BOTTOM, TOP_LEFT, BOTTOM, RIGHT_BOTTOM, LEFT_RIGHT_BOTTOM, LEFT_BOTTOM, LEFT
}
