package com.aa_software.farm_adventure.model.game_object;

public enum Irrigation {
	TOP, BOTTOM, LEFT, RIGHT, TOP_LEFT, TOP_RIGHT, TOP_BOTTOM, BOTTOM_LEFT,
	BOTTOM_RIGHT, LEFT_RIGHT, TOP_LEFT_RIGHT, BOTTOM_LEFT_RIGHT,
	TOP_BOTTOM_LEFT, TOP_BOTTOM_RIGHT, TOP_BOTTOM_LEFT_RIGHT
}
